services:
  - type: web
    name: agrivision-backend
    env: python
    repo: https://github.com/Dhanush2002-28/cropwise-harvest-navigator.git
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
